mestagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('', views.index, name="index"),
    path('detail/<int:post_id>', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    path('new/', views.new, name="new"),
]

posts/models.py
from django.db import models

class Post(models.Model):
    author = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField()

    def __str__(self):
        return f'{self.author}: {self.content}'

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.utils import timezone

def index(request):
    posts = Post.objects.all()
    context= {'posts':posts}
    return render(request, 'posts/index.html', context)

def detail(request, post_id):
    post = Post.objects.get(id = post_id)
    context = {'post':post}
    return render(request, 'posts/detail.html', context)

def create(request):
    return render(request, 'posts/create.html')

def new(request):
    new_post = Post(
        author = request.POST['author'], 
        content = request.POST['content'], 
        created_at=timezone.now()
        )
    new_post.save()

    return redirect('posts:detail', post_id=new_post.id)


    

posts/templates/posts/create.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <title>Mestagram</title>
    </head>
    <body>
        <h1>Mestagram 글쓰기</h1>
        <form action="{%url 'posts:new'%}" method="POST">
        {% csrf_token %}
            <div> 작성자 : </div>
            <input type="text" name="author"/>
            <div> 본문 : </div>
            <textarea name="content"></textarea>
            <div>
                <button type="submit">포스팅</button>
            </div>
        </form>
    </body>
</html>

posts/templates/posts/detail.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <title>Mestagram</title>
        <link rel="stylesheet" href="{% static 'posts/style.css' %}" >
    </head>
    <body>
        <h1>Mestagram</h1>
        <div><a href="{%url 'posts:index'%}">피드로 돌아가기</a></div>
        <div>
            <div>{{post.author}}</div>
            <img width='300' src="{% static 'posts/images/sample.png'%}" />
            <div>{{post.created_at}}</div>
            <div>{{post.content}}</div>
            <div><a href="">삭제하기</a></div>
            <div><a href="">수정하기</a></div>
        </div>
    </body>
</html> 

posts/templates/posts/index.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <title>Mestagram</title>
        <link rel="stylesheet" href="{% static 'posts/style.css' %}" >
    </head>
    <body>
        <h1>Mestagram</h1>
        <a href="{%url 'posts:create'%}">글쓰기</a>
        {%for post in posts%}
        <div class="card">
            <div>{{post.author}}</div>
            <img width='300' src="{% static 'posts/images/sample.png'%}" />
            <div>{{post.created_at}}</div>
            <div>{{post.content}}</div>
            <div><a href="{%url 'posts:detail' post.id%}">상세보기</a></div>
        </div>
        {%endfor%}
    </body>
</html>